CREATE TABLE roles (
  id BIGSERIAL PRIMARY KEY,
  nom VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  telephone VARCHAR(20),
  password TEXT NOT NULL,
  role_id BIGINT NOT NULL REFERENCES roles(id),
  date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE formations (
  id BIGSERIAL PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  description TEXT,
  categorie VARCHAR(100),
  prix NUMERIC(12, 2) NOT NULL DEFAULT 0,
  formateur_id BIGINT NOT NULL REFERENCES users(id),
  image TEXT,
  video_intro TEXT,
  date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE modules (
  id BIGSERIAL PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  ordre INTEGER NOT NULL DEFAULT 0,
  formation_id BIGINT NOT NULL REFERENCES formations(id) ON DELETE CASCADE
);

CREATE TABLE lecons (
  id BIGSERIAL PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  contenu TEXT,
  type VARCHAR(50) NOT NULL,
  ordre INTEGER NOT NULL DEFAULT 0,
  module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE
);

CREATE TABLE ressources (
  id BIGSERIAL PRIMARY KEY,
  url TEXT NOT NULL,
  type VARCHAR(50) NOT NULL,
  lecon_id BIGINT NOT NULL REFERENCES lecons(id) ON DELETE CASCADE
);

CREATE TABLE inscriptions (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  formation_id BIGINT NOT NULL REFERENCES formations(id) ON DELETE CASCADE,
  statut VARCHAR(50) NOT NULL DEFAULT 'EN_ATTENTE',
  date_inscription TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, formation_id)
);

CREATE TABLE progressions (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lecon_id BIGINT NOT NULL REFERENCES lecons(id) ON DELETE CASCADE,
  complete BOOLEAN NOT NULL DEFAULT FALSE,
  score NUMERIC(5, 2),
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, lecon_id)
);

CREATE TABLE quiz (
  id BIGSERIAL PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  formation_id BIGINT NOT NULL REFERENCES formations(id) ON DELETE CASCADE
);

CREATE TABLE questions (
  id BIGSERIAL PRIMARY KEY,
  question TEXT NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'QCM',
  points NUMERIC(5, 2) NOT NULL DEFAULT 1,
  quiz_id BIGINT NOT NULL REFERENCES quiz(id) ON DELETE CASCADE
);

CREATE TABLE reponses (
  id BIGSERIAL PRIMARY KEY,
  texte TEXT NOT NULL,
  correcte BOOLEAN NOT NULL DEFAULT FALSE,
  question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id BIGSERIAL PRIMARY KEY,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  contenu TEXT NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  titre VARCHAR(255) NOT NULL,
  contenu TEXT NOT NULL,
  lu BOOLEAN NOT NULL DEFAULT FALSE,
  date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paiements (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  formation_id BIGINT NOT NULL REFERENCES formations(id),
  montant NUMERIC(12, 2) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  reference VARCHAR(150) NOT NULL UNIQUE,
  statut VARCHAR(50) NOT NULL DEFAULT 'INITIE',
  date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE certificats (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  inscription_id BIGINT NOT NULL REFERENCES inscriptions(id) ON DELETE CASCADE,
  url_pdf TEXT NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, inscription_id)
);

INSERT INTO roles (nom)
VALUES ('ADMIN'), ('FORMATEUR'), ('APPRENANT')
ON CONFLICT (nom) DO NOTHING;
